# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3ba8aac412efd0f4f322c46139f006fa6133fa8b9d442ea5a93e1d3d894442653d42b7d2916aa0dd7cadea533cd78819b6185973b97034ac0cbcf95ff82516e

test:
  secret_key_base: 6be8607e72434a760a9cffa9de926624e06ca1bf287655228798226a851788ccbbc72b55fd165fb0f48651bc5dc45b4b1b27c09578632498ababdd7d45af5aef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
